homepage/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('mine/', views.mine, name='mine'),
    path('new/', views.post_new, name='post_new'),
    path('show/', views.post_list, name='post_list'),
    
    
    url(r'show/(?P<pk>[0-9]+)/delete/$', views.Delete.as_view(),name='delete'),
]

story/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Post(models.Model):
    hari= models.CharField(max_length=10)
    tanggal= models.DateField()
    jam= models.TimeField()
    namaKegiatan = models.CharField(max_length=200)
    tempat = models.CharField(max_length=50)
    kategori= models.CharField(max_length=20)
    

    def __str__(self):
        return self.namaKegiatan
        
    def deftanggal(self):
        return self.tanggal.strftime('%d')
    def bulan(self):
        return self.tanggal.strftime('%b')
   

homepage/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['hari', 'tanggal', 'jam', 'namaKegiatan', 'tempat', 'kategori']
        widgets = {
                    'hari': forms.TextInput(),
                    'tanggal': forms.TextInput(attrs={'placeholder': 'YYYY-MM-DD'}),
                    'jam': forms.TextInput(attrs={'placeholder': 'HH-MM'}),
                    'namaKegiatan': forms.TextInput(), 'tempat':forms.TextInput(), 'kategori':forms.TextInput()
                }
        
        
        
    def __init__(self, *args, **kwargs):
        super(PostForm,self).__init__(*args,**kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
        

homepage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import PostForm
from .models import Post
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView



def index(request):
    return render(request, 'index.html')
def mine(request):
    return render(request, 'mine.html')
def post_list(request):
    postlist = Post.objects.all()
    return render(request, 'post_list.html', {'postlist': postlist})    
    
def post_new(request):
    if request.method == "POST":
           form = PostForm(request.POST)
           if form.is_valid():
               post = form.save()
               post.save()
               return redirect('/show/')
    else:
        form = PostForm()
    return render(request, 'post_edit.html', {'form': form})
    

class Delete(DeleteView):
    model=Post
    success_url=reverse_lazy('homepage:post_list')

homepage/templates/base.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<html>
<head>
	<title>Nazila Rahma</title>
	
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" >
	<link href="{% static 'style.css' %}" rel="stylesheet" type="text/css" >
	
	
	
	<link href="https://fonts.googleapis.com/css?family=Chilanka&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
	<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
</head>
<body>
		<nav class="navbar navbar-expand-lg warnaNavbar fixed-top">
	  		<a class="navbar-brand" href="{% url 'homepage:index' %}"> HOME</a>
			<a class="navbar-brand" href="{% url 'homepage:mine' %}"> GALLERY</a>
			<a class="navbar-brand" href="{% url 'homepage:post_new' %}"> FORM </a>
			<a class="navbar-brand" href="{% url 'homepage:post_list' %}"> SCHEDULE</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
	  		</button>
	  		<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
	    	<div class="navbar-nav ml-auto">
	      <a class="nav-item nav-link">Nazila Rahma</a> 
	    </div>
	  </div>
	</nav>
	{% block content %}
	{% endblock %}
	<div class="fixed">
	    <a href="mailto:nazilarhmh@gmail.com" ><img src="https://cdn3.iconfinder.com/data/icons/social-circle/512/647403-email-512.png" height="40" width="40" ></a>
		  <a href="https://www.linkedin.com/in/nazilarahma/" target="_blank"> <img src="https://cdn3.iconfinder.com/data/icons/social-circle/512/social_7-128.png" height="40" width="40" ></a>
		  <a href="https://www.instagram.com/nazilarhm/" target="_blank"> <img src="https://cdn3.iconfinder.com/data/icons/social-circle/512/social_6-128.png" height="40" width="40" ></a>
	      <a href="https://www.facebook.com/profile.php?id=100002749623591" target="_blank"><img src="https://cdn3.iconfinder.com/data/icons/social-circle/512/social_3-128.png" height="40" width="40" ></a>
		  <a href="https://www.youtube.com/channel/UCPxMVS6f8NMtUXE0Irp8W3w?view_as=subscriber" target="_blank"><img src="https://cdn3.iconfinder.com/data/icons/social-circle/512/647397-youtube-128.png" height="40" width="40" ></a>
	  </div>
</body>
</html>

homepage/templates/index.html
{% extends 'base.html' %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<html>


<body>
	{% block content %}
	<div class="home"  id="index">
		Welcome
	</div>
	
   	<div class="about" id="about">
   	 <h2> <span class="label label-default h2">About</span></h2><br>
   	 <p>Hello! my name is Nazila Rahma. You can call me Nazila. i'm 19 years old. I'm a student at the Faculty of Computer Science in the University of Indonesia. I am a friendly person, and i'm flexible to work at any time and place.  If you want to know more about me, just contact me! </p><br>
   	 <br><h3> <span class="label label-default h3"> Education Details</span></h2><br>
        <p>MI Adabiyah 2 Palembang<br>
        SMP LTI IGM Palembang<br>
        SMA N 3 Palembang<br>
        Universitas Indonesia</p><br>
   	 <br><h3> <span class="label label-default h3"> My Interest</span></h2><br>
	  	
   	         <img src="{% static 'microphone-sing.png' %}"  class="gambar rounded-circle">
   	     	 <img src="{% static 'guitar-icon-png-27.png' %}" class="gambar rounded-circle">
   	     	   <img src="{% static 'trip-icon-20.png' %}"  class="gambar rounded-circle">  
   			   <p>since I was a kid, I like music. I like to sing, and I like to play guitar. Besides that, I also really like traveling and shopping.</p><br> 
			    
   	<br><h3> <span class="label label-default h3">Skills</span></h2><br>
           <img src="{% static 'logo.png' %}"  class="gambar rounded-circle">
       	 <img src="{% static 'js.png' %}"  class="gambar rounded-circle">
       	   <img src="{% static 'html.png' %}"  class="gambar rounded-circle">
         	 <img src="{% static 'css.png' %}"  class="gambar rounded-circle">
         	   <img src="{% static 'jv.png' %}"  class="gambar rounded-circle">
   		   <br>
   	<div clas="container">
   	    <div class="row">
   	      <div class="col">
   	        <br><br><h3> <span class="label label-default h3">Organization</span></h2><br>
   				<div class="d-flex flex-row">
   				    <img src="{% static 'sistem.png' %}"  class="gambar1 rounded-circle">
   				    <p class="or">SISTEM Fasilkkom UI<br>Information Management</p><br>
   				 </div>
   				 <div class="d-flex flex-row">
   				<img src="{% static 'fuki.png' %}" class="gambar1 rounded-circle">
   				<p class="or">FUKI Fasilkom UI<br>Corporation</p>
   			</div>
			   
   	      </div>
   	      <div class="col">
   	        <br><br><h3> <span class="label label-default h3">Experience</span></h2><br>
   					<div class="d-flex flex-row">
   					    <img src="{% static 'cft.png' %}"  class="gambar1 rounded-circle">
   					    <p class="or">COMPFEST<br>Editorial Marketinng</p><br>
   					 </div>
   					 <div class="d-flex flex-row">
   					<img src="{% static 'siwak.png' %}"  class="gambar1 rounded-circle">
   					<p class="or">SIWAK-NG<br>Accomodation</p>
   				</div>
   	      </div>
   	    </div>
   	</div>
	
    </div>
 
 
{% endblock %}
</body>
{% load staticfiles %}
</html>

homepage/templates/mine.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<html>


<body>
	{% block content %}	

 <div class="gallery-foto" id="gallery">
	<br><br><br><h2> <span class="label label-default h2">Gallery</span></h2><br>
 	<div class="foto-1">
		<img src="{% static 'IMG_4667.jpg' %}">
		<img src="{% static 'IMG-4860.jpg' %}">
		<img src="{% static 'IMG-4553.jpg' %}">
		<div class="text">
			Bromo
		</div>
 	</div>
	
 	<div class="foto-2">
		<div class="text">
			Family
		</div>
		<img src="{% static 'fam.jpg' %}">
		<img src="{% static 'fam1.jpg' %}">
 	   	<img src="{% static 'rsp.jpg' %}" >
 	   	
 	</div>
 	<div class="foto-1">
		<img src="{% static 'IMG-6610.jpg' %}">
		<img src="{% static 'IMG-6674.jpg' %}">
		<img src="{% static 'IMG-6726.jpg' %}">
		<div class="text">
			Maribaya
		</div>
 	</div>
 	<div class="foto-2">
		<div class="text">
			Friends
		</div>
		<img src="{% static 'IMG-2051.jpg' %}">
		<img src="{% static 'IMG-1453.jpg' %}">
		<img src="{% static 'IMG-3478.jpg' %}">
 	</div>
</div>
	 <div class="poetry" id="poetry">
		<br><br><br><h2> <span class="label label-default h2">Poetry</span></h2><br>
		<h3> <span class="label label-default h3">Biru</span></h2><br>

		<p>
		Sewindu di ruang sama semu<br>
		Dengan rasa berlika-liku<br>
		Dengan seiring waktu<br>
		Mulai jinak diriku<br>
		Maksud baik hati tuk mu<br>
		Tapi terlalu,<br>
		Hingga salah waktu<br>	
		Begitu cepat jatuhku<br>
		dengan niat awal tak begitu.<br>
		Kukira kau lambaikanku,<br>
		Tuk cerita tentang kalbu<br>
		Ternyata kau hanya butuh<br>
		Tuk lampiaskan tangismu<br>
		Yang telah lama dihantu.<br>
		Padahal telah kututup pintu<br>
		Agar makhluk tak ingin aku<br>
		Hingga harus kutahu<br>
		Bahwa kau bukan menunggu<br>	
		</p>

		<br><h3> <span class="label label-default h3">Berdakwah dari Hati</span></h2><br>

		<p>Dakwah bukan tentang siapa yang lebih islami<br>
			Juga bukan perkara siapa yang suci<br>
			Namun dakwah perintah sang ilahi<br>J
			uga ajaran dari sang para nabi<br>
	Tak apa walau hanya sedikit arti<br>
	Daripada diri tertusuk duri?<br>
	Dakwah adalah cinta dari hati<br>
	Mengajak insan perbaiki diri<br>
	Bersama melangkah surga abadi<br>
	Dakwah juga perihal mengobati<br>
	Tentang noda yang berapi-api<br>
	Meluruskan tikungan tajam tinggi<br>
	Membangun kedamaian negeri<br>
	Dengan para pemuda pemudi<br>
	Jangan menunggu hal tak pasti<br>
	Jangan juga menanti datangnya mati<br>
	Mari memulai tanpa kata nanti<br>
	Meski sedikit sulit dilampaui<br> 
	Menuju suci kita jalani  <br> <br> <br> <br> <br></p>
	 </div>
{% endblock %}
</body>
{% load staticfiles %}
  </html>

homepage/templates/post_edit.html
{% extends 'base.html' %}
{% load static %}

<html>
<body>
{% block content %}

<div class="post container">
	<div class="col-xl-6">
<br><br><br>
    <h2> <span class="label label-default h2">Schedule</span></h2>
	<br>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="label label-default h3 save btn btn-default">Save</button>
		<br><br>
    </form>
</div>
</div>

{% endblock %}
</body>
{% load staticfiles %}
</html>

homepage/templates/post_list.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<html>
<body>
	{% block content %}
<div class="show post container">
	<div class= "col-xl-6">
	<br><br><br><br>
	{% for post in postlist %}
		<div class="row row-striped">
					<div class="col-2 text-right">
						<h1 class="display-4"><span class="badge badge-secondary">{{ post.deftanggal }}</span></h1>
						<h2>{{ post.bulan }}</h2>
					</div>
					<div class="col-10">
						<h3 class="text-uppercase"><strong>{{ post.namaKegiatan }}</strong></h3>
						<ul class="list-inline">
						    <li class="list-inline-item"><i class="fa fa-calendar-o" aria-hidden="true"></i> {{ post.hari }}</li>
							<li class="list-inline-item"><i class="fa fa-clock-o" aria-hidden="true"></i> {{ post.jam }}</li>
							<li class="list-inline-item"><i class="fa fa-location-arrow" aria-hidden="true"></i> {{ post.tempat }}</li>
						</ul>
						<p>{{ post.kategori }}</p>
					</div>
					
				</div>
				<form action="{% url 'homepage:delete' post.id %}" method="post">
					{% csrf_token %}
				    <input type="hidden" name="post_id" value="{{ post.id }}"/>
				        <button type="" class="btn btn-info " style="margin-left: 30%;" >
							
				         Hapus
				        </button> 
				</form>
	{% endfor %}
	<br>
		
		<br><br><br><br>
	</div>
</div>
{% endblock %}
</body>
{% load staticfiles %}
</html>